### ISSUE TITLE
Azur Lane Adapter Error

### ISSUE THREAD

**Issue by RoonMoonlight** [KaikyuLotus/moe-moe-secretary#19]
Hello, there is Out of Bounds error for Azur Lane Bremerton adapter.

Here is the log:
```
Loading default config first
Found custom config file, loading it...
Starting AzurLane with name Bremerton
Registered on boot
Getting ship quotes
Getting ship images
Parsing data...
Loading dialogs
Loading dialogs of language Chinese
com.kitsunecode.mms.core.entities.exceptions.StartFailedException: Critical error while creating the adapter: IndexOutOfBoundsException: Index: 0, Size: 0
	at com.kitsunecode.mms.core.utils.Util.getWaifuFromAdapterName(Util.java:249)
	at com.kitsunecode.mms.core.Main.lambda$initialize$0(Main.java:37)
	at com.kitsunecode.mms.core.utils.Util.catchMoeMoeExceptionsAndExit(Util.java:339)
	at com.kitsunecode.mms.core.Main.initialize(Main.java:35)
	at com.kitsunecode.mms.core.Main.main(Main.java:45)
Caused by: com.kitsunecode.mms.core.entities.exceptions.StartFailedException: IndexOutOfBoundsException: Index: 0, Size: 0
	at com.kitsunecode.mms.core.adapters.IWaifuAdapter.init(IWaifuAdapter.java:68)
	at com.kitsunecode.mms.core.utils.Util.getWaifuFromAdapterName(Util.java:234)
	... 4 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.remove(ArrayList.java:498)
	at com.kitsunecode.mms.core.adapters.impl.AzurLane.loadDialogs(AzurLane.java:86)
	at com.kitsunecode.mms.core.adapters.impl.AzurLane.loadDialogs(AzurLane.java:74)
	at com.kitsunecode.mms.core.adapters.impl.AzurLane.loadFromCustomSource(AzurLane.java:58)
	at com.kitsunecode.mms.core.adapters.IWaifuAdapter.init(IWaifuAdapter.java:50)
	... 5 more
```

**Comment by RoonMoonlight** [comment]
It also happens to Enterprise... I guess whole Azur Lane adapters got broke because of their update
